name = "tribus-monitor-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
MONITOR_CHECKS_TOKEN = "tribus-monitor-token-2026-7kP4mQ9xL2vN8dR5"
MONITOR_COVERAGE_TOKEN = "oHlcifn-cM-afrHpog8AYQFstscCrKcJznXCZx8d5FI"
MONITOR_E2E_TOKEN = "tribus-monitor-token-2026-7kP4mQ9xL2vN8dR5"

[[d1_databases]]
binding = "DB"
database_name = "tribus_monitor_db"
database_id = "3f29acd4-b9a4-4aa0-a877-da11fd890a73"
