name = "tribus-monitor-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "tribus_monitor_db"
database_id = "3f29acd4-b9a4-4aa0-a877-da11fd890a73"
